version: "3"
services:
    feed:
        build:
            context: "./feed"
            dockerfile: Dockerfile
        container_name: "feed"
        volumes:
            - ./config.json:/usr/src/app/config.json
        depends_on:
            - mongo
            - backend
        links:
            - mongo
        env_file:
            - .env

    backend:
        build:
            context: "./backend"
            dockerfile: Dockerfile
        container_name: backend
        depends_on:
            - mongo
        restart: "always"
        ports:
            - "3000:3000"
        links:
            - mongo
        env_file:
            - .env
        volumes:
            - ./app.log:/usr/src/app/app.log
            - ./404.log:/usr/src/app/404.log
            - ./error.log:/usr/src/app/error.log
            - ./mock-data.json:/usr/src/app/mock-data.json
            - ./watchlist.txt:/usr/src/app/watchlist.txt
    mongo:
        image: mongo
        container_name: "mongo-container"
        environment:
            - MONGO_INITDB_DATABASE=Users
            - MONGO_INITDB_ROOT_USERNAME=sammy
            - MONGO_INITDB_ROOT_PASSWORD=123456
        volumes:
            - ./data:/data/db
        ports:
            - "27017:27017"
